### ISSUE TITLE
Is this library stable/still being maintained?

### ISSUE THREAD

**Issue by dave08** [VansPo/state-machine#1]
It looks like there's lots of potential to it. But was only updated 2 years ago...? Btw, are you on the Kotlin slack?

**Comment by dave08** [comment]
Now it seems like there's a 401 error "No read access to this repo" from Jitpack... :(, right after I started migrating my code to this lib...

**Comment by dave08** [comment]
In the end I had to add this to gradle... it seems to be a mistake in the core dependency name...

```
configurations.all {
    resolutionStrategy.eachDependency {
        if (requested.group == "com.github.vanspo" && requested.name == "state-machine-core") {
            useTarget("com.github.vanspo:state-machine:${requested.version}")
            because("fixes mistake in dependency name")
        }
    }
}
```

**Comment by VansPo** [comment]
Hi Dave! 
Sorry for not replying for so long. As you've probably guessed by now, this library is not maintained, as I'm not active on GitHub these days. Thank you for catching my mistake!
